- name: stop polkadot service
  systemd:
    name: polkadot.service
    state: stopped

- name: purge chain
  shell: |
    set -o pipefail
    /usr/local/bin/polkadot purge-chain -y
  become: yes
  become_user: polkadot
  args:
    executable: /bin/bash
  changed_when: False

- name: start polkadot service
  systemd:
    name: polkadot.service
    state: started
