- hosts: all
  become: yes
  strategy: free
  roles:
  - { role: node-exporter, when: "node_exporter_enabled|default(false)|bool == true" }
  - vpnpeer-setup
  - polkadot-common

- hosts: all
  become: yes
  roles:
  - vpnpeer
  - common

- hosts: public
  become: yes
  roles:
  - polkadot-public

- hosts: validator
  become: yes
  roles:
  - polkadot-validator
  - polkadot-validator-session-info
